version: '3.8'

services:
  frontend-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: instantmart/frontend_admin:latest
    container_name: ecommerce_frontend_admin
    restart: always
    networks:
      - ecommerce-network
    expose:
      - "80"

  nginx:
    image: nginx:stable-alpine
    container_name: ecommerce_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend-admin
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge