version: '3.8'

services:
  frontend-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: instantmart/frontend_admin:latest
    container_name: ecommerce_frontend_admin
    restart: always
    ports:
      - "80:80"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge